name: metadata
description: metadata helps to extract metadata from your files.
version: 2.0.0
homepage: https://github.com/justkawal/metadata.git

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  xmp: ^1.0.1

dev_dependencies:
  test: ^1.14.4
